server:
  port: 9000

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3306/jmshop_mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: junmokang
      password: wnsah12

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: update
      use-new-id-generator-mappings: true
    open-in-view: false

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/order.log
    max-history: 30

  level:
    root: INFO



