# HTTP config
PRODUCT_SERVER_IP: localhost
PRODUCT_SERVER_PORT: 9001

READ_TIME_OUT: 180000  # 3분
CONN_TIME_OUT: 180000 # 3분
MAX_CONN_TOTAL: 500
MAX_CONN_PER_ROUTE: 100

# Lock Config
WAIT_TIME: 60 # 60sec
LEASE_TIME: 120 # 120sec